### ISSUE TITLE
[BE/BUG] RabbitMq 스프링 연결 관련 로직 확인 필요

### ISSUE THREAD

**Issue by junglesub** [handong-app/CMS#235]
## ✅ 이슈 체크리스트

- [ ] 제목에 작업 파트 추가 ([FE] 또는 [BE] Prefix 추가)

## 🐞 버그 설명

스프링에서 MQ 큐가 없을 경우 충돌이나 연결 실패가 됩니다.

### 추측:

1. 실행이 됐는데 없으면 -> 충돌
2. 실행 중에 없어지면 -> 무시

### 해결방법

**1. application.yml 수정**

```yml
listener:
  simple:
    missing-queues-fatal: false
    retry:
      enabled: true               # (선택) 연결 재시도 활성화
      initial-interval: 2000ms
      max-attempts: 5
      multiplier: 2.0
```

**2. 없으면 자동 생성 되도록**

```java
@Bean
public Queue transcodeStatusQueue(@Value("${TRANSCODE_STATUS_QUEUE}") String name) {
    return new Queue(name, true); // durable = true
}
```

___ 

## 🎥 재현 방법

* RabbitMQ 에 `transcode.status` 큐가 없으면 스프링에서 오류나 무시가 됨. (있다가 없어지는 것 포함)

___ 

## 📸 스크린샷/에러 메시지

___ 

## 🌐 환경 정보
-  앱/버전: 
- 브라우저/OS: 
- 디바이스: 
- 기타:
